spring:
  h2:
    console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url : jdbc:h2:mem:encryptiondemo
    username: sa
    password: password
  jpa:
    properties:
          hibernate:
            globally_quoted_identifiers: true
            globally_quoted_identifiers_skip_column_definitions: true
            dialect: org.hibernate.dialect.H2Dialect